name: car_platform_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  get:
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.7.0
  google_maps_flutter_web: ^0.5.8
  geolocator_web: ^4.0.0
  image_picker: ^1.1.2
  mysql_client: ^0.0.27
  google_maps_flutter_platform_interface: ^2.8.0
  geocoding: ^3.0.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  get_storage: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/logo.png
      - assets/images/cpu/amd ryzen 3.jpg
      - assets/images/cpu/amd ryzen 5.jpg
      - assets/images/cpu/amd ryzen 7.png
      - assets/images/cpu/AMD ryzen 9.jpg
      - assets/images/cpu/intel core i9.jpg
      - assets/images/cpu/intel i3.jpg
      - assets/images/cpu/intel i5.jpg
      - assets/images/cpu/intel i7.jpg
      - assets/images/cpu/intel xeon.jpg
      - assets/images/cpu/threadripper.jpg

      - assets/images/gpu/rtx 3080.jpg
      - assets/images/gpu/amd 6800.jpg
      - assets/images/gpu/rtx3070.jpg
      - assets/images/gpu/amd 6700.jpg
      - assets/images/gpu/rtx3060.jpg
      - assets/images/gpu/6600.jpg
      - assets/images/gpu/gtx1660.jpg
      - assets/images/gpu/amd 590.jpg
      - assets/images/gpu/gtx1080.jpg
      - assets/images/gpu/amd580.jpg

      - assets/images/Ram/consair 16.jpg
      - assets/images/Ram/gskill z 16.jpg
      - assets/images/Ram/kingston hyper 16.jpg
      - assets/images/Ram/samsung 16.jpg
      - assets/images/Ram/crucial ballistix.jpg
      - assets/images/power/consair rm 750.jpg
      - assets/images/power/evga supernova 750.jpg
      - assets/images/power/seasonic focus.jpg
      - assets/images/power/Cooler Master MWE 850.jpg
      - assets/images/power/consair rm 850.jpg
      - assets/images/power/850.jpg
      - assets/images/power/seasonic focus.jpg
      - assets/images/power/coolermaster mwe 750.jpg
      - assets/images/power/Corsair RM1000.jpg
      - assets/images/power/EVGA SuperNOVA 1000.jpg

      - assets/images/monitor/Samsung Odyssey G7.jpg
      - assets/images/monitor/LG UltraGear 27GL850.jpg
      - assets/images/monitor/Dell Alienware AW2720HF.jpg
      - assets/images/monitor/Acer Predator XB273K.jpg
      - assets/images/monitor/ASUS ROG Swift PG27UQ.jpg
      - assets/images/monitor/Samsung Odyssey G9.jpg
      - assets/images/monitor/LG UltraGear 34GN850.jpg
      - assets/images/monitor/Dell UltraSharp U2720Q.jpg
      - assets/images/monitor/Acer Nitro XV272U.jpg
      - assets/images/monitor/ASUS TUF Gaming VG27AQ.jpg

      - assets/images/mouse/Logitech G502.jpg
      - assets/images/mouse/Razer DeathAdder V2.jpg
      - assets/images/mouse/SteelSeries Rival 600.jpg
      - assets/images/mouse/Logitech G903.jpg
      - assets/images/mouse/Razer Viper Ultimate.jpg
      - assets/images/mouse/steelSeries Sensei 310.jpg
      - assets/images/mouse/Logitech G Pro.jpg
      - assets/images/mouse/Razer Naga Trinity.jpg
      - assets/images/mouse/SteelSeries Aerox 3.jpg
      - assets/images/mouse/Logitech MX Master 3.jpg

      - assets/images/keyboard/Corsair K65 RGB.jpg
      - assets/images/keyboard/Razer BlackWidow Elite.jpg
      - assets/images/keyboard/Corsair K70 RGB.jpg
      - assets/images/keyboard/SteelSeries Apex Pro.jpg
      - assets/images/keyboard/Corsair K95 RGB.jpg
      - assets/images/keyboard/Razer Huntsman Elite.jpg
      - assets/images/keyboard/Logitech G513.jpg
      - assets/images/keyboard/SteelSeries Apex 7.jpg
      - assets/images/keyboard/Logitech G915.jpg
      - assets/images/keyboard/Razer Cynosa V2.jpg

      - assets/images/background.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
